### ISSUE TITLE
When the chat is active messages don't appear instantaneously

### ISSUE THREAD

**Issue by hamzabinamin** [customerly/Customerly-Android-SDK#1]
When the support chat is open, the messages don't appear on the recipients side unless they go back and open the chat again.

**Comment by hamzabinamin** [comment]
@pmusolino @lucamicheli @danieleratti @emdotem 

Can you please look into this?

**Comment by giannign1** [comment]
Hi there,
i am sorry i have not clear a thing
Are you experiencing this issue from the sdk side, i mean inside the support chat in your android app or in your Customerly Android App ?

**Comment by hamzabinamin** [comment]
It happens on both. The support chat was on an Android app while the customerly app was installed on an iOS device.

If a customer sends a message using the support app. The iOS customerly app sends out the notification however as soon as the admin becomes active on the chat and replies to the customer. The customer doesn't see the message until he goes back and opens the chat screen again. Samething happens on the customerly app.

**Comment by giannign1** [comment]
So the customer needs to go back and go in the conversation again to see the new messages

AND

the admin too, in customerly IOS app has to go back and back in to load the new messages?

**Comment by hamzabinamin** [comment]
Yes exactly.

**Comment by giannign1** [comment]
Thank you for reporting @hamzabinamin ,
i have just uploaded the version 3.0.2 of the Android SDK that will fix those bugs (reflected in the apps too)
Enjoy :D

**Comment by hamzabinamin** [comment]
@giannign1 Awesome, I'll test it out and report back. Can you take a look at the other open issue as well? Even if I specify the custom color for the support chat window, it always appears red no matter what color I specify.
