### ISSUE TITLE
Color for support activity doesn't change even after specifying a custom color

### ISSUE THREAD

**Issue by hamzabinamin** [customerly/Customerly-Android-SDK#2]

**Comment by giannign1** [comment]
Hi, i am looking into this
How did you specify the color?
Can i please see the code? Thanks

**Comment by giannign1** [comment]
it is working for me...
if i can check your code, maybe the documentation about how using it was not so clear?

**Comment by hamzabinamin** [comment]
I checked the new update, both issues have been fixed thanks :)
You definitely did something for the color thing as well, I was using `getColor(R.color.myColor)` to get the color int.

I have noticed a new more bugs:
1. If I specify the email of the user before starting the support activity, it doesn't take that email and shows a random name like RoyalBlue Ocelot even though I do set the email. I have tried logging out and re logging like the sdk says but it doesn't help. However if I don't specify an email through code then the support activity asks for the email and registers that email correctly.

2. If I open the chat window for the admin (on the website dashboard) and reply the customer, the admin message doesn't get delivered to the customer unless he goes back and open the chat window again. But its working correctly now for the admin app on android.

3. Another thing I noticed was that if the customer goes back to a previous chat and the admin messages him first, that very first message doesn't get delivered to the customer. If the admin messages again for the second time, it gets delivered fine. (this was on the customerly admin android app).

4. Lastly even if I login as a new user or with a new name it shows the previous chats of the previous user. I mean if I login with the email address (abc@gmail.com) and I logout and relogin using a different email (bca@gmail.com), shouldn't it remove the previous chats that were added for abc?

Thanks again for the quick response.

**Comment by hamzabinamin** [comment]
@giannign1 did you get a chance to look at these mate?

**Comment by giannign1** [comment]
not yet i'll keep you posted about it

**Comment by giannign1** [comment]
@hamzabinamin about the first point, can i see your code? Because is working for me

Any chances you are doing something like this? (without wait some time between the first and the second?

> Customerly.logoutUser()
> Customerly.registerUser(email)

**Comment by giannign1** [comment]
I only succeded to replicate your first issue by writing
```
Customerly.logoutUser()
Customerly.registerUser(email)
```
That's because the logoutUser was not intended as a blocking task but it it executed asynchronously and will conflict with the registerUser task

If you need to perform something like this, i just added a callback to the logoutUser() function so, since next version of SDK you'll be able to write:
```
Customerly.logoutUser {
    Customerly.registerUser(email)
}
```

**Comment by hamzabinamin** [comment]
@giannign1 

No I am not calling them both together one after the other. The call layout is as following:

1. User logs out of their account.
2. We call `Customerly.logoutUser`
3. The user logs in to their account (Its a network call to our own server now)
4. if the login is successful, we register the user in Customerly as well using `Customerly.registerUser(email)`

As you can see there's quite a difference in call time so it shouldn't be happening. Plus logout feature works fine. If I log out and initiate the chat, the support activity prompts me to enter a email.

**Comment by giannign1** [comment]
Strange is not happening to me
I have just uploaded a new version of sdk,  3.0.3
Let me know if some of the reported bugs persist

**Comment by hamzabinamin** [comment]
@giannign1 Rest of the bugs seem to be fixed but the register function is still not working correctly. I still get random names for customers.

Also I posted an issue for the ios version as well. I think  you're active there as well. Could you take a look on that as well?

**Comment by giannign1** [comment]
I am sorry i need to see your code of logout, registerUser and openSupport as well because is working in my test app, maybe i can see a way to replicate the issue. Thank you

For the other task no i don't handle ios but i pushed the ios developer, he will answer asap

**Comment by hamzabinamin** [comment]
@giannign1 

Logout function

   ```
 public void showLogOutDialog() {
        AlertDialog.Builder builder;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            builder = new AlertDialog.Builder(context, R.style.DialogStyle);
        } else {
            builder = new AlertDialog.Builder(context);
        }
        builder.setTitle(context.getString(R.string.logout2))
                .setMessage(context.getString(R.string.areYouSureYouWantToLogout))
                .setPositiveButton(R.string.logout, new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int which) {
                        if(Shared_Preferences.getCurrentCustomer(context) != null) {
                            Customer customer = Shared_Preferences.getCurrentCustomer(context);

                            if(customer.facebookUser) {
                                System.out.println("Facebook User is logging out");
                                LoginManager.getInstance().logOut();
                            }
                            else {
                                System.out.println("Non Facebook User is logging out");
                            }
                        }
                        Shared_Preferences.saveCurrentCustomer(context, null);
                        **Customerly.logoutUser();**
                        TastyToast.makeText(context, context.getString(R.string.logoutConfirmation), TastyToast.LENGTH_SHORT, TastyToast.SUCCESS);
                         ((AccountActivity)context).getFragmentManager().popBackStack(null, FragmentManager.POP_BACK_STACK_INCLUSIVE);
                         ((AccountActivity)context).startActivity(new Intent(context, MainActivity.class));
                    }
                })
                .setNegativeButton(android.R.string.no, new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int which) {
                        dialog.cancel();
                    }
                })
                .show();
    }
```

Login Function

  ```
 public static void getCustomerUsingEmailAndPassword(final Context context, String email, String password, final KProgressHUD hud) {

        Gson gson = new GsonBuilder()
                .setLenient()
                .create();

        Retrofit.Builder builder = new Retrofit.Builder()
                .baseUrl("http://xxx/App Scripts/")
                .addConverterFactory(GsonConverterFactory.create(gson));

        Retrofit retrofit = builder.build();

        CustomerInterface customerInterface = retrofit.create(CustomerInterface.class);
        Call<JsonObject> call = customerInterface.getCustomerUsingEmailAndPassword(email, password);
        call.enqueue(new Callback<JsonObject>() {
            @Override
            public void onResponse(Call<JsonObject> call, Response<JsonObject> response) {
                Utilities.hideHUD(hud);
                System.out.println("Response: " + response.body().toString());
                String status = response.body().getAsJsonPrimitive("status").getAsString();

                if(status.equals("success")) {
                    JsonArray userArray = response.body().getAsJsonArray("user");
                    System.out.println(userArray.get(0).getAsJsonObject().get("ID").getAsString());
                    Customer customer = new Customer(userArray.get(0).getAsJsonObject().get("ID").getAsString(), userArray.get(0).getAsJsonObject().get("Email").getAsString(), userArray.get(0).getAsJsonObject().get("Password").getAsString());
                    customer.firstname = userArray.get(0).getAsJsonObject().get("First_Name").getAsString();
                    customer.lastname = userArray.get(0).getAsJsonObject().get("Last_Name").getAsString();
                    customer.number = userArray.get(0).getAsJsonObject().get("Contact_Number").getAsString();
                    customer.postal = userArray.get(0).getAsJsonObject().get("Postal_Code").getAsString();
                    customer.street = userArray.get(0).getAsJsonObject().get("Street_Address").getAsString();
                    customer.omiseID = userArray.get(0).getAsJsonObject().get("Omise_ID").getAsString();

                    Shared_Preferences.saveCurrentCustomer(context, customer);
                    Utilities.sendMessage(context, true);
                    **Customerly.registerUser(email);**
                    ((AccountActivity)context).getSupportFragmentManager().popBackStackImmediate();
                    ((AccountActivity)context).hideTabLayout();
                    ((AccountActivity)context).showFragment(new SettingsFragment());
                }
                else if(status.equals("wrong password")) {
                    TastyToast.makeText(context, context.getString(R.string.wrongPassword), TastyToast.LENGTH_SHORT, TastyToast.ERROR);
                }
                else if(status.equals("failure")) {
                    TastyToast.makeText(context, context.getString(R.string.wrongEmailPassword), TastyToast.LENGTH_SHORT, TastyToast.CONFUSING);
                }
            }

            @Override
            public void onFailure(Call<JsonObject> call, Throwable t) {
                Utilities.hideHUD(hud);
                System.out.println("Failed: " + t.getMessage());
                TastyToast.makeText(context, context.getString(R.string.somethingWentWrong), TastyToast.LENGTH_SHORT, TastyToast.CONFUSING);
            }
        });

    }
```

Open Support Function

```
      switch (view.getId()) {
            case R.id.emailNowButton:
                sendEmail();
                break;

            case R.id.chatButton:
                Customerly.openSupport(getActivity());
                break;
        }

```

**Comment by giannign1** [comment]
Your code seems okay for me 👍 
So can you tell me the steps you are following?
i did the following:
Customerly.logoutUser(); //Just to make sure we start with zero authentication
wait 1s
Customerly.openSupport(getActivity());
write a message (received with random names)
Customerly.logoutUser();
wait 1s
Customerly.registerUser(email);
write a message (received with email user)
Customerly.logoutUser();
write a message (received with random name 'XXX YYY')
Customerly.registerUser(email); (the old lead 'XXX YYY' get upgraded to user email)
previous message from 'XXX YYY' is now from 'email user'
write a message (received with email user)

which is the step not working well for you?

**Comment by hamzabinamin** [comment]
@giannign1  I cleared cache and reinstalled the app, the logout feature is working as intended now. I'll keep an eye in case the issue comes again.

Can you please ask the iOS developer to look into my other request. Its been 7 days and he didn't comment there. Would appreciate a lot. Thanks
